DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS city CASCADE;

CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL UNIQUE,
    address TEXT NOT NULL,
    city BIGINT,
    FOREIGN KEY (city) REFERENCES city(id) 
);

CREATE TABLE city (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name  TEXT NOT NULL
);
